services:

  api-gateway:
    container_name: api-gateway
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ../api-gateway/.env
    networks:
      - cust_network

networks:
  cust_network:
    driver: bridge