services:

  api-gateway:
    container_name: api-gateway
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ../api-gateway/.env
    networks:
      - cust_network
    volumes:
      - ./uploads:/app/uploads

  wc-gateway:
    container_name: wc-gateway
    build:
      context: ../wc-gateway
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - ../wc-gateway/.env
    networks:
      - cust_network

networks:
  cust_network:
    driver: bridge