services:
  start-frontend:
    container_name: start-frontend
    build:
      context: ../start-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../start-frontend/.env
    depends_on:
      - api-gateway
    networks:
      - cust_network

  service-frontend:
    container_name: service-frontend
    build:
      context: ../service-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ../service-frontend/.env
    depends_on:
      - api-gateway
    networks:
      - cust_network

  api-gateway:
    container_name: api-gateway
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ../api-gateway/.env
    networks:
      - cust_network

networks:
  cust_network:
    driver: bridge